package application.model;
// Generated Dec 4, 2021, 8:58:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import application.utils.BankAccountValidate;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name = "bank_account", schema = "public")
public class BankAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String cardNumber;
	private Customer customer;
	private String cardholderName;
	private String securityCode;
	private Date expirationDate;
	private String issueBank;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public BankAccount() {
	}

	public BankAccount(String cardNumber, Customer customer, String cardholderName, String securityCode,
			Date expirationDate, String issueBank) {
		this.cardNumber = cardNumber;
		this.customer = customer;
		this.cardholderName = cardholderName;
		this.securityCode = securityCode;
		this.expirationDate = expirationDate;
		this.issueBank = issueBank;
	}

	@Id

	@Column(name = "card_number", unique = true, nullable = false)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_code", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "cardholder_name", nullable = false)
	public String getCardholderName() {
		return this.cardholderName;
	}

	public void setCardholderName(String cardholderName) {
		this.cardholderName = cardholderName;
	}

	@Column(name = "security_code", nullable = false)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", nullable = false, length = 13)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "issue_bank", nullable = false)
	public String getIssueBank() {
		return this.issueBank;
	}

	public void setIssueBank(String issueBank) {
		this.issueBank = issueBank;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bankAccount")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}
	
	public String validate() {
		BankAccountValidate bankAccountValidate = new BankAccountValidate(this);
		return bankAccountValidate.validateBankAccount();
	}

}
