package application.model;
// Generated Dec 4, 2021, 8:58:47 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", schema = "public")
public class Transaction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private TransactionId id;
	private BankAccount bankAccount;
	private Bill bill;
	private int amount;
	private String description;
	// 1 - transfer money from customer bank to system, 0 - transfer money from system to customer bank
	private int typeTransaction;

	public Transaction() {
	}

	public Transaction(TransactionId id, BankAccount bankAccount, Bill bill, int amount, int typeTransaction) {
		this.id = id;
		this.bankAccount = bankAccount;
		this.bill = bill;
		this.amount = amount;
		this.typeTransaction = typeTransaction;
	}

	public Transaction(TransactionId id, BankAccount bankAccount, Bill bill, int amount, String description, int typeTransaction) {
		this.id = id;
		this.bankAccount = bankAccount;
		this.bill = bill;
		this.amount = amount;
		this.typeTransaction = typeTransaction;
		this.description = description;
		this.typeTransaction = typeTransaction;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "billCode", column = @Column(name = "bill_code", nullable = false)),
			@AttributeOverride(name = "cardNumber", column = @Column(name = "card_number", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 13)) })
	public TransactionId getId() {
		return this.id;
	}

	public void setId(TransactionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "card_number", nullable = false, insertable = false, updatable = false)
	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bill_code", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	// 1 - transfer money from customer bank to system, 0 - transfer money from system to customer bank
	@Column(name = "type_transaction")
	public int getTypeTransaction() {
		return typeTransaction;
	}

	public void setTypeTransaction(int typeTransaction) {
		this.typeTransaction = typeTransaction;
	}

}
