package application.model;
// Generated Dec 4, 2021, 8:58:47 PM by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionId generated by hbm2java
 */
@Embeddable
public class TransactionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int billCode;
	private String cardNumber;
	private Timestamp date;

	public TransactionId() {
	}

	public TransactionId(int billCode, String cardNumber, Timestamp date) {
		this.billCode = billCode;
		this.cardNumber = cardNumber;
		this.date = date;
	}

	@Column(name = "bill_code", nullable = false)
	public int getBillCode() {
		return this.billCode;
	}

	public void setBillCode(int billCode) {
		this.billCode = billCode;
	}

	@Column(name = "card_number", nullable = false)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "date", nullable = false)
	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionId))
			return false;
		TransactionId castOther = (TransactionId) other;

		return (this.getBillCode() == castOther.getBillCode())
				&& ((this.getCardNumber() == castOther.getCardNumber()) || (this.getCardNumber() != null
						&& castOther.getCardNumber() != null && this.getCardNumber().equals(castOther.getCardNumber())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBillCode();
		result = 37 * result + (getCardNumber() == null ? 0 : this.getCardNumber().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
